# Generated by Django 2.2.12 on 2021-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_socialconnectivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
