# Generated by Django 2.2.12 on 2021-06-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_postsmodel_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='message',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
